# Generated by Django 4.2.7 on 2023-11-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_alter_fads_decade_alter_fads_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decades',
            new_name='Decade',
        ),
        migrations.RenameModel(
            old_name='Fads',
            new_name='Fad',
        ),
    ]
